"""Fold batch norm, quantise weights per output channel and export.

Writes:
- src/weights.ts: widths and the weights as text, in the layer order
  src/net.ts reads them. Every value is a base64url character, which
  compresses far better than a packed bitstream (see sizes.py): per
  layer, the weights as zigzagged `bits`-bit integers, one character each,
  then a scale per output channel as one character in quarter-octave steps,
  then a 12-bit bias per output channel as two characters, against the
  layer's bias scale in `biasScales`.
- runs/<run>/quantized.pt: the same dequantised weights as a normal
  checkpoint, so `predict.py --checkpoint` scores exactly what ships.
- test/fixtures/model.json: inputs and logits for a TS parity test.

Usage: python export.py <run> [--bits 6]
"""

import argparse
import base64
import json

import numpy as np
import torch
import torch.nn as nn

from codec import ALPHABET, chars, log_scale, zigzag
from train import ROOT, build, config

REPO = ROOT.parent


def layers(net):
    """(conv, batchnorm or None) pairs in forward order, matching net.ts."""
    convs = [m for m in net.modules() if isinstance(m, nn.Conv2d)]
    bns = {}
    for m in net.modules():
        if isinstance(m, nn.Sequential):
            kids = list(m)
            for a, b in zip(kids, kids[1:]):
                if isinstance(a, nn.Conv2d) and isinstance(b, nn.BatchNorm2d):
                    bns[a] = b
    return [(c, bns.get(c)) for c in convs]


def encode(w, b, bits):
    """One layer as text, plus its dequantised weights and biases."""
    top = 2 ** (bits - 1) - 1
    codes, scale = log_scale(w.reshape(w.shape[0], -1).abs().max(1).values.clamp_min(1e-12) / top)
    q = torch.round(w.reshape(w.shape[0], -1) / scale[:, None]).clamp(-top, top)
    # Shortest float that round-trips well enough, written as is to weights.ts
    bias_scale = float(f"{float(b.abs().max().clamp_min(1e-9)) / 2047:.5g}")
    bq = torch.round(b / bias_scale).clamp(-2047, 2047)
    text = chars(zigzag(q)) + chars(codes) + "".join(ALPHABET[v >> 6] + ALPHABET[v & 63] for v in zigzag(bq))
    return text, bias_scale, (q * scale[:, None]).reshape(w.shape), bq * bias_scale


def fold(conv, bn):
    w = conv.weight.detach().clone()
    b = conv.bias.detach().clone() if conv.bias is not None else torch.zeros(w.shape[0])
    if bn is not None:
        k = bn.weight.detach() / torch.sqrt(bn.running_var + bn.eps)
        w = w * k[:, None, None, None]
        b = bn.bias.detach() + (b - bn.running_mean) * k
    return w, b


def fixture_inputs(size):
    """Deterministic synthetic scenes: gradients, blobs and noise."""
    rng = np.random.default_rng(7)
    ys, xs = np.mgrid[0:size, 0:size] / size
    out = []
    for cx, cy, r in [(0.7, 0.35, 0.12), (0.3, 0.65, 0.2)]:
        img = np.stack([0.3 + 0.3 * ys, 0.5 - 0.2 * xs, 0.4 + 0.1 * xs * ys])
        blob = ((xs - cx) ** 2 + (ys - cy) ** 2) < r * r
        img[:, blob] = np.array([0.9, 0.2, 0.15])[:, None]
        img += rng.normal(0, 0.04, img.shape)
        out.append((np.clip(img, 0, 1) * 255).round().astype(np.uint8))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("run")
    ap.add_argument("--bits", type=int, default=6)
    ap.add_argument("--checkpoint")
    args = ap.parse_args()
    run = ROOT / "runs" / args.run
    c = config(args.run)
    net = build(c)
    net.load_state_dict(torch.load(args.checkpoint or run / "best.pt", map_location="cpu"))
    net.eval()
    text, bias_scales = [], []
    for conv, bn in layers(net):
        w, b = fold(conv, bn)
        t, bias_scale, w, b = encode(w, b, args.bits)
        text.append(t)
        bias_scales.append(bias_scale)
        # Put the dequantised, folded weights back: BN becomes "+ bias"
        with torch.no_grad():
            conv.weight.copy_(w)
            if bn is not None:
                bn.weight.fill_(1)
                bn.bias.copy_(b)
                bn.running_mean.zero_()
                bn.running_var.fill_(1 - bn.eps)
            else:
                conv.bias.copy_(b)
    torch.save(net.state_dict(), run / "quantized.pt")
    (REPO / "src" / "weights.ts").write_text(
        f"// Generated by train/export.py from run {args.run}, {args.bits}-bit weights\n"
        f"export const input = {c['input']}\n"
        f"export const bits = {args.bits}\n"
        f"export const widths = {json.dumps(c['widths']).replace(' ', '')}\n"
        f"export const biasScales = {json.dumps(bias_scales).replace(' ', '')}\n"
        f"export const weights =\n  '{''.join(text)}'\n"
    )
    inputs = fixture_inputs(c["input"])
    with torch.no_grad():
        x = torch.from_numpy(np.stack(inputs)).float() / 255
        logits = net(x).numpy()
    (REPO / "test" / "fixtures").mkdir(exist_ok=True)
    (REPO / "test" / "fixtures" / "model.json").write_text(
        json.dumps(
            {
                "size": c["input"],
                "inputs": [base64.b64encode(i.tobytes()).decode() for i in inputs],
                "logits": [[round(float(v), 5) for v in l.flatten()] for l in logits],
            }
        )
    )
    print(f"{sum(map(len, text))} characters of weights, {sum(p.numel() for p in net.parameters())} parameters")


if __name__ == "__main__":
    main()
